kind: pipeline
type: docker
name: release-egui-wasm-builder

trigger:
  event:
    - tag
  ref:
    - refs/tags/egui-wasm-builder-v*

steps:
  - name: build and push egui-wasm-builder
    image: plugins/docker
    settings:
      registry: registry.local.frudd.dev
      repo: registry.local.frudd.dev/egui-wasm-builder
      tags:
        - latest
        - ${DRONE_TAG##egui-wasm-builder-v}
      dockerfile: ./roggo_web/trunk_builder/Dockerfile
      context: ./roggo_web/trunk_builder/.

---
kind: pipeline
type: docker
name: release-roggo-web

trigger:
  event:
    - tag
  ref:
    - refs/tags/roggo-web-v*

steps:
  - name: build and push roggo-web
    image: plugins/docker
    settings:
      registry: registry.public.frudd.dev:10443
      repo: registry.public.frudd.dev:10443/roggo-web
      tags:
        - latest
        - ${DRONE_TAG##roggo-web-v}
      build_args:
        - APP_VERSION=${DRONE_TAG##roggo-web-v}
      dockerfile: ./roggo_web/Dockerfile
      context: ./roggo_web/.

  - name: deploy staging
    image: appleboy/drone-ssh
    depends_on:
      - build and push roggo-web
    settings:
      host: homepage.local.frudd.dev
      username: fish
      password:
        from_secret: local_docker_ssh_password
      port: 22
      script:
        - cd /home/fish/docker/roggo-web/
        - echo "ROGGO_WEB_VERSION=${DRONE_TAG##roggo-web-v}" > .env
        - docker compose pull
        - docker compose up -d

---
kind: pipeline
type: docker
name: promote-roggo-web-prod

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: deploy production
    image: appleboy/drone-ssh
    settings:
      host: registry.public.frudd.dev
      username: whale
      password:
        from_secret: public_docker_ssh_password
      port: 21622
      script:
        - cd /home/whale/docker/roggo/
        - echo "ROGGO_WEB_VERSION=${DRONE_TAG##roggo-web-v}" > .env
        - docker compose pull
        - docker compose up -d