kind: pipeline
type: docker
name: release-roggo-stats

trigger:
  event:
    - tag
  ref:
    - refs/tags/roggo-stats-v*

steps:
  - name: build and push ballchasing-wrapper
    image: plugins/docker
    settings:
      registry: registry.local.frudd.dev
      repo: registry.local.frudd.dev/ballchasing-wrapper
      tags:
        - latest
        - ${DRONE_TAG##roggo-stats-v}
      build_args:
        - APP_VERSION=${DRONE_TAG##roggo-stats-v}
      dockerfile: ./RoggoStats/BallchasingWrapper/Dockerfile
      context: ./RoggoStats/BallchasingWrapper/.

  - name: build and push roggo-discord-bot
    image: plugins/docker
    settings:
      registry: registry.local.frudd.dev
      repo: registry.local.frudd.dev/roggo-discord-bot
      tags:
        - latest
        - ${DRONE_TAG##roggo-stats-v}
      build_args:
        - APP_VERSION=${DRONE_TAG##roggo-stats-v}
      dockerfile: ./RoggoStats/RoggoDiscordBot/Dockerfile
      context: ./RoggoStats/RoggoDiscordBot/.

  - name: deploy
    image: appleboy/drone-ssh
    depends_on:
      - build and push ballchasing-wrapper
      - build and push roggo-discord-bot
    settings:
      host: homepage.local.frudd.dev
      username: fish
      password:
        from_secret: local_docker_ssh_password
      port: 22
      script:
        - cd /home/fish/docker/roggo-stats/
        - docker compose pull
        - docker compose up -d

---
kind: pipeline
type: docker
name: release-egui-wasm-builder

trigger:
  event:
    - tag
  ref:
    - refs/tags/egui-wasm-builder-v*

steps:
  - name: build and push egui-wasm-builder
    image: plugins/docker
    settings:
      registry: registry.local.frudd.dev
      repo: registry.local.frudd.dev/egui-wasm-builder
      tags:
        - latest
        - ${DRONE_TAG##egui-wasm-builder-v}
      dockerfile: ./RoggoStats/roggo_live_service/trunk_builder/Dockerfile
      context: ./RoggoStats/roggo_live_service/trunk_builder/.

---
kind: pipeline
type: docker
name: release-roggo-web

trigger:
  event:
    - tag
  ref:
    - refs/tags/roggo-web-v*

steps:
  - name: build and push roggo-web
    image: plugins/docker
    settings:
      registry: registry.public.frudd.dev:10443
      repo: registry.public.frudd.dev:10443/roggo-web
      tags:
        - latest
        - ${DRONE_TAG##roggo-web-v}
      build_args:
        - APP_VERSION=${DRONE_TAG##roggo-web-v}
      dockerfile: ./RoggoStats/roggo_live_service/Dockerfile
      context: ./RoggoStats/roggo_live_service/.

  - name: deploy staging
    image: appleboy/drone-ssh
    depends_on:
      - build and push roggo-web
    settings:
      host: homepage.local.frudd.dev
      username: fish
      password:
        from_secret: local_docker_ssh_password
      port: 22
      script:
        - cd /home/fish/docker/roggo-web/
        - echo "ROGGO_WEB_VERSION=${DRONE_TAG##roggo-web-v}" > .env
        - docker compose pull
        - docker compose up -d

---
kind: pipeline
type: docker
name: promote-roggo-web-prod

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: deploy production
    image: appleboy/drone-ssh
    settings:
      host: registry.public.frudd.dev
      username: whale
      password:
        from_secret: public_docker_ssh_password
      port: 21622
      script:
        - cd /home/whale/docker/roggo/
        - echo "ROGGO_WEB_VERSION=${DRONE_TAG##roggo-web-v}" > .env
        - docker compose pull
        - docker compose up -d