kind: pipeline
type: docker
name: release-roggo-web

trigger:
  event:
    - tag
  ref:
    - refs/tags/roggo-web-v*

steps:
  - name: build and push roggo-web
    image: plugins/docker
    settings:
      registry: registry.local.frudd.dev
      repo: registry.local.frudd.dev/roggo-web
      tags:
        - latest
        - ${DRONE_TAG##roggo-web-v}
      build_args:
        - APP_VERSION=${DRONE_TAG##roggo-web-v}
      dockerfile: ./RoggoStats/roggo_live_service/Dockerfile
      context: ./RoggoStats/roggo_live_service/.


  - name: deploy
    image: appleboy/drone-ssh
    depends_on:
      - build and push roggo-web
    settings:
      host: homepage.local.frudd.dev
      username: fish
      password:
        from_secret: local_docker_ssh_password
      port: 22
      script:
        - cd /home/fish/docker/roggo-web/
        - docker compose pull
        - docker compose up -d