volumes:
  mongo_data_volume:
networks:
  rl_stats_network:
services:
  ballchasing_db:
    image: mongo
    ports:
      - '29017:27017'
    container_name: ballchasing_db
    networks:
      - rl_stats_network
    volumes:
      - mongo_data_volume:/data/db
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=BallchasingWrapper
      - MONGO_INITDB_ROOT_PASSWORD=chaser
  
  ballchasing_wrapper:
    image: ballchasing-wrapper:latest
    ports:
      - '9000:9000'
    container_name: ballchasing_wrapper
    networks:
      - rl_stats_network
    depends_on:
      ballchasing_db:
        condition: service_started
    environment:
      - BALLCHASING_API_KEY=${BALLCHASING_API_KEY}
      - MONGO_HOST=ballchasing_db
      - MONGO_PORT=27017
      - MONGO_USER=BallchasingWrapper
      - MONGO_PASSWORD=chaser
      - DATABASE_NAME=RoggoData