@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for the Roggo Agent
System_Ext(rl_api, "Rocket League Game API")
System_Ext(wasm_app, "WASM App")
ComponentDb(sqlite, "Sqlite DB")

System_Boundary(roggo_agent, "Roggo Agent"){
    Component(agent, "Agent", "", "Head of the agent")
    Component(aggregator, "Aggregator", "", "Chops API stream into game sections")
    Component(game_stat_collector, "Game Stat Collector", "", "Collects stats for one game")
    Component(roggo_api, "Roggo API", "http", "Provides game stats")
    Rel(rl_api, agent, "sends TCP Strings")
    Rel(agent, aggregator, "forwards raw packet strings")
    Rel(agent, wasm_app, "forwards raw event strings")
    Rel(aggregator, game_stat_collector, "forwards deserialized events")
    Rel(game_stat_collector,aggregator, "returns game stats")
    Rel(aggregator, sqlite, "saves game stats")
    Rel(agent, roggo_api, "starts")
    Rel(wasm_app, roggo_api, "fetches historical stats")
    Rel(roggo_api, sqlite, "loads historical stats")
}


SHOW_LEGEND()
@enduml