pub fn map_arena(arena: &str) -> &str {
    match arena {
        "Underwater_P" => "AquaDome",
        "Underwater_GRS_P" => "AquaDome (Salty Shallows)",
        "Park_P" => "Beckwith Park",
        "Park_Night_P" => "Beckwith Park (Midnight)",
        "Park_Rainy_P" => "Beckwith Park (Stormy)",
        "mall_day_p" => "Boostfield Mall",
        "cs_p" => "Champions Field",
        "cs_day_p" => "Champions Field (Day)",
        "outlaw_p" => "Deadeye Canyon",
        "Outlaw_Oasis_P" => "Deadeye Canyon (Oasis)",
        "Stadium_P" => "DFH Stadium",
        "Stadium_Race_Day_P" => "DFH Stadium (Circuit)",
        "stadium_day_p" => "DFH Stadium (Day)",
        "Stadium_Foggy_P" => "DFH Stadium (Stormy)",
        "STADIUM_10A_P" => "DFH Stadium (10th Anniversary)",
        "woods_p" => "Drift Woods",
        "Woods_Night_P" => "Drift Woods (Night)",
        "FF_Dusk_P" => "Estadio Vida",
        "farm_p" => "Farmstead",
        "Farm_Night_P" => "Farmstead (Night)",
        "Farm_HW_P" => "Farmstead (Spooky)",
        "Farm_GRS_P" => "Farmstead (Pitched)",
        "CHN_Stadium_P" => "Forbidden Temple",
        "CHN_Stadium_Day_P" => "Forbidden Temple (Day)",
        "FNI_Stadium_P" => "Forbidden Temple (Fire & Ice)",
        "UF_Day_P" => "Futura Garden",
        "UF_Night_P" => "Futura Garden (Night)",
        "EuroStadium_P" => "Mannfield",
        "EuroStadium_Dusk_P" => "Mannfield (Dusk)",
        "EuroStadium_Night_P" => "Mannfield (Night)",
        "EuroStadium_Rainy_P" => "Mannfield (Stormy)",
        "NeoTokyo_Standard_P" => "Neo Tokyo",
        "NeoTokyo_Toon_P" => "Neo Tokyo (Comic)",
        "NeoTokyo_Hax_P" => "Neo Tokyo (Hacked)",
        "NeoTokyo_Arcade_P" => "Neo Tokyo (Arcade)",
        "music_p" => "Neon Fields",
        "Paname_Dusk_P" => "Parc de Paris",
        "beach_P" => "Salty Shores",
        "beach_night_p" => "Salty Shores (Night)",
        "Beach_Night_GRS_P" => "Salty Shores (Salty Fest)",
        "street_p" => "Sovereign Heights",
        "ARC_Darc_P" => "Starbase ARC (Aftermath)",
        "TrainStation_P" => "Urban Central",
        "TrainStation_Dawn_P" => "Urban Central (Dawn)",
        "TrainStation_Night_P" => "Urban Central (Night)",
        "UtopiaStadium_P" => "Utopia Coliseum",
        "UtopiaStadium_Dusk_P" => "Utopia Coliseum (Dusk)",
        "UtopiaStadium_Lux_P" => "Utopia Coliseum (Gilded)",
        "wasteland_s_p" => "Wasteland",
        "wasteland_Night_S_P" => "Wasteland (Night)",
        "Wasteland_GRS_P" => "Wasteland (Pitched)",

        "ARC_P" => "Arctagon",
        "Wasteland_P" => "Badlands",
        "Wasteland_Night_P" => "Badlands (Night)",
        "NeoTokyo_P" => "Tokyo Underpass",
        "throwbackstadium_P" => "Throwback Stadium",

        "Labs_4v4_Arena15_EuroStadium_Night_P" => "Mannfield (Quads)",
        "Labs_4v4_Arena15_Blackout_P" => "Midnight Metro (Quads)",
        "Labs_4v4_Arena15_Retro_P" => "Sunset Dunes (Quads)",

        "Labs_PillarHeat_P" => "Barricade",
        "Labs_Basin_P" => "Basin",
        "Labs_PillarWings_P" => "Colossus",
        "Labs_Corridor_P" => "Corridor",
        "Labs_Cosmic_V4_P" => "Cosmic",
        "Labs_DoubleGoal_V2_P" => "Double Goal",
        "Labs_Galleon_P" => "Galleon",
        "Labs_Galleon_Mast_P" => "Galleon Retro",
        "Labs_PillarGlass_P" => "Hourglass",
        "Labs_Holyfield_P" => "Loophole",
        "Labs_Octagon_02_P" => "Octagon",
        "Labs_CirclePillars_P" => "Pillars",
        "Labs_Underpass_P" => "Underpass",
        "Labs_Utopia_P" => "Utopia Retro",
        "cs_hw_p" => "Rivals Arena",
        "Labs_Octagon_B2B_02_P" => "Roadblock",

        "HoopsStadium_P" => "Dunk House",
        "hoopsStreet_p" => "The Block",

        "Park_Snowy_P" => "Beckwith Park (Snowy)",
        "Stadium_Winter_P" => "DFH Stadium (Snowy)",
        "eurostadium_snownight_p" => "Mannfield (Snowy)",
        "UtopiaStadium_Snow_P" => "Utopia Coliseum (Snowy)",
        "throwbackhockey_p" => "Throwback Stadium (Snowy)",

        "arc_standard_p" => "Starbase ARC (Rumble)",
        "ShatterShot_P" => "Core 707",

        map => map,
    }
}
