INSERT INTO player_stats (
    match_guid,
    team_num,
    player_id,
    shortcut,
    score,
    goals,
    shots,
    assists,
    saves,
    touches,
    car_touches,
    demos,
    time_boosting,
    time_demolished,
    time_on_ground,
    time_on_wall,
    time_powersliding,
    time_supersonic
  )
VALUES (
    -- 'match_guid:uuid',
    ?1,
    -- team_num:INTEGER,
    ?2,
    -- 'player_id:TEXT',
    ?3,
    -- shortcut:INTEGER,
    ?4,
    -- score:INTEGER,
    ?5,
    -- goals:INTEGER,
    ?6,
    -- shots:INTEGER,
    ?7,
    -- assists:INTEGER,
    ?8,
    -- saves:INTEGER,
    ?9,
    -- touches:INTEGER,
    ?10,
    -- car_touches:INTEGER,
    ?11,
    -- demos:INTEGER,
    ?12,
    -- time_boosting:INTEGER,
    ?13,
    -- time_demolished:INTEGER,
    ?14,
    -- time_on_ground:INTEGER,
    ?15,
    -- time_on_wall:INTEGER,
    ?16,
    -- time_powersliding:INTEGER,
    ?17,
    -- time_supersonic:INTEGER
    ?18
  );