name: RoggoStatsDevEnv

volumes:
  dev_db:
  dev_configdb:
services:
  ballchasing_db:
    image: mongo:8.2.6
    ports:
      - '29017:27017'
    container_name: ballchasing_db
    volumes:
      - dev_db:/data/db
      - dev_configdb:/data/configdb
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=BallchasingWrapper
      - MONGO_INITDB_ROOT_PASSWORD=chaser